import { useState } from 'react';

function Disclaimer({ variant = 'default' }) {
  const [expanded, setExpanded] = useState(false);

  // Use the calm info callout style for landing page
  if (variant === 'landing') {
    return (
      <div className="info-callout">
        <div className="info-callout-header" onClick={() => setExpanded(!expanded)}>
          <div className="info-callout-title">
            <span className="info-callout-icon">ℹ️</span>
            <span>Important: This is guidance, not therapy</span>
          </div>
          <button className="info-callout-toggle" type="button">
            {expanded ? 'Show less' : 'Read more'}
          </button>
        </div>
        {expanded && (
          <div className="info-callout-content">
            <p>
              Repair Coach provides AI-powered relationship guidance for educational purposes only.
              We are not licensed therapists or mental health professionals.
            </p>
            <p>
              Our guidance should not replace professional therapy, especially for serious
              relationship trauma, mental health concerns, or situations involving abuse.
            </p>
            <p>
              By using this service, you acknowledge that results may vary and that you are
              responsible for seeking appropriate professional help when needed.
            </p>
          </div>
        )}
      </div>
    );
  }

  // Default style for questionnaire pages
  return (
    <div className="disclaimer">
      <h4>Important Notice</h4>
      <p>
        This tool is for educational and coaching purposes only. It is NOT a substitute for
        professional therapy or counseling from a licensed mental health provider.
      </p>
      <p>
        The advice provided is generated by AI and should not be considered professional
        medical or psychological advice. We strongly recommend working with a licensed
        therapist, especially when dealing with relationship trauma.
      </p>
      <p>
        By continuing, you acknowledge that no guarantees of outcomes are made, and you
        understand the limitations of AI-generated guidance.
      </p>
    </div>
  );
}

export default Disclaimer;
