function Disclaimer() {
  return (
    <div className="disclaimer">
      <h4>Important Notice</h4>
      <p>
        This tool is for educational and coaching purposes only. It is NOT a substitute for
        professional therapy or counseling from a licensed mental health provider.
      </p>
      <p>
        The advice provided is generated by AI and should not be considered professional
        medical or psychological advice. We strongly recommend working with a licensed
        therapist, especially when dealing with relationship trauma.
      </p>
      <p>
        By continuing, you acknowledge that no guarantees of outcomes are made, and you
        understand the limitations of AI-generated guidance.
      </p>
    </div>
  );
}

export default Disclaimer;
